"use client";

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tcrntflauzdxypeeaanj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRjcm50ZmxhdXpkeHlwZWVhYW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA3MjkyMDYsImV4cCI6MjA4NjMwNTIwNn0.vgA-SE8thXsgpd96rjNNTJxJhg_BnBKrZgKNnFT7MhY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});